name: on-push-main

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/on-push-main.yaml'
      - '.github/workflows/on-version-tagged.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'functions/**'
      - 'tests/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.14.2
    with:
      examples: |
        [
          { "example": "examples/mongodboperators/minimal.yaml" },
          { "example": "examples/mongodboperators/standard.yaml" }
        ]
      api_path: apis/mongodboperators
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.14.2

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.14.2

  version-and-tag:
    name: Version and Tag
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.20.2
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    with:
      useDeployKey: true